---
- name: Ensure java_type var has acceptable value
  assert:
    that: java_type in [ "headless", "devel" ]
    quiet: yes

- name: Ensure java_version var has acceptable value for EL7
  assert:
    that:
      - java_version in ['1.8.0', '11']
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int < 8

- name: Ensure java_version var has acceptable value for EL8
  assert:
    that:
      - java_version in ['1.8.0', '11', '17']
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8

- name: "Ensure {{ java_package }} package is installed"
  yum:
    name: "{{ java_package }}"
    state: present
