---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9-ubi-init}-java-${JAVA_VERSION:-11}"
    hostname: java
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  env:
    JAVA_VERSION: ${JAVA_VERSION:-11}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint